# Development overrides for docker-compose
version: '3.8'

services:
  server:
    build:
      target: dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  client:
    build:
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0